### ISSUE TITLE
Miscellaneous Cluster Reporting Bugs

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#480]
- [x]  Should location be in 'Add Project' ?

#Resolved. We are not including 'add project' - Seth

![Screen Shot 2018-02-21 at 3.38.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f26b7191a37bf111234f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df742e34853a013346ae07f2431.png)

- [x] We should Add a ‘No report data associated with this indicator has been submitted yet.’ for any indicator (Cluster activity, partner project & activity). Would want same in analysis tab as well if working.
Do this for IP reporting indicators tab as well.

![screen shot 2018-02-16 at 2 19 54 pm](https://user-images.githubusercontent.com/31295242/36336440-a94e1fd2-133c-11e8-91e1-49b6e55dd38f.png)

- [x]  @marcindo we unchecked this ticket. Saving is working on the backend, but when you go to edit it, the Location field are not displaying the current value

![Screen Shot 2018-02-21 at 2.27.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f26b7191a37af1102c4f5a595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df742e34857a41a3061ef712431.png)

- [x]  @rkrupinski Data not showing in 3 level disaggregation. This prevents entered data

```
non_field_errors: ["Submitted disaggregation data entries contains extra combination pair keys"]}
non_field_errors
:
["Submitted disaggregation data entries contains extra combination pair keys"]


```
![Screen Shot 2018-02-21 at 3.01.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f26b7191a37bf1122a4f5c565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df742e34851a6103564e67f2431.png)

- [x]  UX improvement. Once data is successfully entered on disaggregations table, please update achievement in reporting period field.

![Screen Shot 2018-02-21 at 3.10.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f26b7191a37bf1132b4f5c565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df742e34851a3133166e0742431.png)

- [x] Remove Locations on project details view

![Screen Shot 2018-02-26 at 1.26.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f56b7191a379f1102d4f5a5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df742e74555a0163067e7732431.png)

**Comment by rkrupinski** [comment]
Branch: `misc-cluster-reporting-bugs-#480`

**Comment by marcindo** [comment]
`Activity Indicator Continuously Loads - Polymer bug` This is also fixed on staging

**Comment by maciej-jaworski** [comment]
Fix for that Cluster Activity Indicator save issue is on separate branch, PR #484

**Comment by sethgold8** [comment]
@maciej-jaworski Regarding adding a cluster indicator. We received this 500 error message:

```
TypeError at /api/indicator/cluster-indicator/
get_by_natural_key() missing 1 required positional argument: 'model'

Request Method: POST
Request URL: http://prp.tivixlabs.com/api/indicator/cluster-indicator/
Django Version: 1.11.5
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.6.4
Python Path: ['.', '', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages', '/code/django_api/apps/', '/code', '/code']
Server time: Wed, 21 Feb 2018 00:26:57 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_swagger',
 'drfpasswordless',
 'django_filters',
 'djcelery',
 'leaflet',
 'suit',
 'easy_pdf',
 'django_cron',
 'account',
 'cluster',
 'core',
 'indicator',
 'partner',
 'unicef',
 'debug_toolbar',
 'django_extensions']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']


Traceback:  

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  489.             response = self.handle_exception(exc)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in handle_exception
  449.             self.raise_uncaught_exception(exc)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  486.             response = handler(request, *args, **kwargs)

File "/code/django_api/apps/indicator/views.py" in post
  588.         if not serializer.is_valid():

File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py" in is_valid
  237.                 self._validated_data = self.run_validation(self.initial_data)

File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py" in run_validation
  432.         value = self.to_internal_value(data)

File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py" in to_internal_value
  462.                 validated_value = field.run_validation(primitive_value)

File "/usr/local/lib/python3.6/site-packages/rest_framework/fields.py" in run_validation
  754.         return super(CharField, self).run_validation(data)

File "/usr/local/lib/python3.6/site-packages/rest_framework/fields.py" in run_validation
  525.         self.run_validators(value)

File "/usr/local/lib/python3.6/site-packages/rest_framework/fields.py" in run_validators
  539.                 validator(value)

File "/code/django_api/apps/core/validators.py" in __call__
  20.         content_type = ContentType.objects.get_by_natural_key(*value.split('.'))

Exception Type: TypeError at /api/indicator/cluster-indicator/
Exception Value: get_by_natural_key() missing 1 required positional argument: 'model'
Request information:
USER: [75]  (admin_imo)

GET: No GET data
```

**Comment by sethgold8** [comment]
[ } - Editing Partner Project fails w/ 400 error message.

```
start_date: ["Date has wrong format. Use one of these formats instead: YYYY[-MM[-DD]]."],…}
end_date
:
["Date has wrong format. Use one of these formats instead: YYYY[-MM[-DD]]."]
start_date
:
["Date has wrong format. Use one of these formats instead: YYYY[-MM[-DD]]."]
0
:
"Date has wrong format. Use one of these formats instead: YYYY[-MM[-DD]]."
```

**Comment by sethgold8** [comment]
- [ ] Adding Partner Activity from cluster activity fails with 500 errror

```
TypeError at /api/partner/43/create-partner-activity/cluster
int() argument must be a string, a bytes-like object or a number, not 'Partner'

Request Method: POST
Request URL: http://prp.tivixlabs.com/api/partner/43/create-partner-activity/cluster
Django Version: 1.11.5
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.6.4
Python Path: ['.', '', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages', '/code/django_api/apps/', '/code', '/code']
Server time: Wed, 21 Feb 2018 00:56:52 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_swagger',
 'drfpasswordless',
 'django_filters',
 'djcelery',
 'leaflet',
 'suit',
 'easy_pdf',
 'django_cron',
 'account',
 'cluster',
 'core',
 'indicator',
 'partner',
 'unicef',
 'debug_toolbar',
 'django_extensions']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']


Traceback:  

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  489.             response = self.handle_exception(exc)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in handle_exception
  449.             self.raise_uncaught_exception(exc)

File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  486.             response = handler(request, *args, **kwargs)

File "/code/django_api/apps/partner/views.py" in post
  185.             if not serializer.is_valid():

File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py" in is_valid
  237.                 self._validated_data = self.run_validation(self.initial_data)

File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py" in run_validation
  435.             value = self.validate(value)

File "/code/django_api/apps/partner/serializers.py" in validate
  255.                 id=data['partner'])

File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py" in get
  371.         clone = self.filter(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py" in filter
  784.         return self._filter_or_exclude(False, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py" in _filter_or_exclude
  802.             clone.query.add_q(Q(*args, **kwargs))

File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py" in add_q
  1250.         clause, _ = self._add_q(q_object, self.used_aliases)

File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py" in _add_q
  1276.                     allow_joins=allow_joins, split_subq=split_subq,

File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py" in build_filter
  1210.             condition = self.build_lookup(lookups, col, value)

File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py" in build_lookup
  1104.                 return final_lookup(lhs, rhs)

File "/usr/local/lib/python3.6/site-packages/django/db/models/lookups.py" in __init__
  24.         self.rhs = self.get_prep_lookup()

File "/usr/local/lib/python3.6/site-packages/django/db/models/lookups.py" in get_prep_lookup
  74.             return self.lhs.output_field.get_prep_value(self.rhs)

File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py" in get_prep_value
  966.         return int(value)

Exception Type: TypeError at /api/partner/43/create-partner-activity/cluster
Exception Value: int() argument must be a string, a bytes-like object or a number, not 'Partner'
Request information:
USER: [76]  (admin_ao)

GET: No GET data

```

**Comment by sethgold8** [comment]
- [ ] Editing custom partner activity fails with 405 error

```
{detail: "Method "PATCH" not allowed."}
detail
:
"Method "PATCH" not allowed."
```

**Comment by maciej-jaworski** [comment]
<img width="1412" alt="screen shot 2018-02-21 at 10 18 51" src="https://user-images.githubusercontent.com/1492815/36472150-2c9037c4-16f1-11e8-8b4f-cb1ef33557cd.png">

- [ ] @marcindo @rkrupinski This modal doesn't display initial data correctly (both frequency and location fields have values assigned to them). I fixed the endpoint used to return that data, frontend needs to be updated to use those.

Fixes are directly on develop branch, commit [458c00d2](https://github.com/unicef/etools-partner-reporting-portal/commit/458c00d2fef6d35670d707b17ba5d48f9b898b2e)

**Comment by maciej-jaworski** [comment]
> We cannot edit indicator because there are no options in 'Location'

This happens when used location has no parent:
https://github.com/unicef/etools-partner-reporting-portal/blob/develop/django_api/django_api/apps/core/views.py#L60

This may be a fakedata issue, maybe @n1207n can confirm.

**Comment by marcindo** [comment]
@sethgold8 @chachra  @maciej-jaworski  I've also noticed that backend can send budget with decimal part e.g. 97356.79 but frontend cannot validate this value as we have simple 'integer only' rule. I could update validation regexp, but do we really need decimal part considering budgets are rather large?

**Comment by maciej-jaworski** [comment]
IMO for consistency we should use decimals with 2 point precision everywhere money is concerned.

**Comment by marcindo** [comment]
Ok, I see only 2 budget fields with currency so will change to accept decimal

**Comment by maciej-jaworski** [comment]
RE: date format - update pushed to develop to accept `21-Feb-2018` as well as the default iso-8601 format (YYYY-MM-DD).

@marcindo please check it works for you

**Comment by maciej-jaworski** [comment]
> Editing custom partner activity fails with 405 error
PR #489 that fixes this added

**Comment by marcindo** [comment]
``` We cannot edit indicator because there are no options in 'Location'``` field should be fixed after #491, if it persists, pretty sure it's because of that children-locations endpoint used there

**Comment by sethgold8** [comment]
@rkrupinski 

- [ ] Data not showing in 3 level disaggregation. This prevents entered data

```
non_field_errors: ["Submitted disaggregation data entries contains extra combination pair keys"]}
non_field_errors
:
["Submitted disaggregation data entries contains extra combination pair keys"]


```
![Screen Shot 2018-02-21 at 3.01.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f26b7191a37bf1122a4f5c565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df742e34851a6103564e67f2431.png)

**Comment by maciej-jaworski** [comment]
`still getting error - Seth` I said the fix was on a separate branch, to be reviewed and merged. Merged it today.

Not a fan of having multiple issues within one, way too messy.

**Comment by sethgold8** [comment]
#worksgood :) - Seth
