### ISSUE TITLE
Error when clicked on PDF link on reports tab under programme documents

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#755]
IP PRP - > https://etools-test.unicef.org/
Chrome browser
Country - > Iraq
Vendor Name - > AGENCY FOR TECHNICAL & EMERGENCY DEV.

Error when clicked on PDF link on reports tab under programme documents

**Comment by KKaselkar** [comment]
@robertavram as per Seth this is fixed in tivixlabs , so we need to redeploy the code in UNICEF test environment
![image](https://user-images.githubusercontent.com/32198614/42097431-1ffdea16-7b86-11e8-8f57-942e5f2a50a5.png)
![image](https://user-images.githubusercontent.com/32198614/42097439-240364d8-7b86-11e8-88e6-e712cbae4eb6.png)

**Comment by robertavram** [comment]
@KKaselkar you said you will retest this... please update this ticket... bug fixing should be the highest priority right now... please make sure cards are updated asap

**Comment by robertavram** [comment]
I believe this has something to do with the reporting period dates being saved before the fix was pushed... if on newly added pds it does not happen, please close this ticket (and 754) as we're not looking to write migrations

**Comment by sethgold8** [comment]
@KKaselkar please confirm if this is working now

**Comment by KKaselkar** [comment]
@sethgold8   error still exists when clicked on Programme document ->reports tab -> PDF export

@robertavram  as per Seth this is fixed in tivixlabs can you please redeploy the code on test environment

**Comment by sethgold8** [comment]
@KKaselkar update on this? IF working, please close

**Comment by KKaselkar** [comment]
working fine.
Resolved
