### ISSUE TITLE
etools test integration with OCHA systems

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#760]
Chrome browser, all workspaces, etools test environment.

User not able to select response plans or add projects from OCHA on etools test environment.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42281040-6a7637cc-7f70-11e8-8e0a-51c8b61a8dd8.png)

**Comment by robertavram** [comment]
Reached out to Dariusz... when he has time.. we'll keep this ticket updated.

**Comment by KKaselkar** [comment]
@robertavram  this is on high priority right now , can you provide  an update on this?

**Comment by robertavram** [comment]
@KKaselkar I was never under the impression that this was no longer high priority... We discovered the bug.. working to fix it.

**Comment by robertavram** [comment]
Done.

**Comment by sethgold8** [comment]
@robertavram , Kunal mentioned this was still broken. If he's wrong, let's close this out. If not can you schedule a call with @dfryta ?

**Comment by sethgold8** [comment]
@KKaselkar just tested.

Looks like its working. If you don't think it is, please let me know links and workspaces (all details needed). Keep in mind OCHA data is not 100% there. Sometimes the integration works, but data is not there from OCHA. 

We can discuss on our call Wed

![Screen Shot 2018-07-10 at 5.02.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f36b7191a37df112294f5e5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54ae34b52a112346ae1772431.png)

![Screen Shot 2018-07-10 at 5.05.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f36b7191a37df1122e4f5d585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54ae34b52a1153065e3732431.png)

**Comment by robertavram** [comment]
@sethgold8 @n1207n there is an issue with the threaded call, sometimes it works sometimes it doesn't... 
```
File "/code/django_api/apps/ocha/imports/bulk.py" in get_response_plans_for_countries
  37.     results = fetch_json_urls_async(urls_to_retrieve)

File "/code/django_api/apps/ocha/imports/bulk.py" in fetch_json_urls_async
  11.     loop = asyncio.get_event_loop()

File "/usr/local/lib/python3.6/asyncio/events.py" in get_event_loop
  694.     return get_event_loop_policy().get_event_loop()

File "/usr/local/lib/python3.6/asyncio/events.py" in get_event_loop
  602.                                % threading.current_thread().name)

Exception Type: RuntimeError at /api/ocha/response-plans/workspace/65/
Exception Value: There is no current event loop in thread 'Thread-9556'.
```

that's the error being thrown...

**Comment by sethgold8** [comment]
@robertavram, @dfryta mentioned the environment is not using uwsgi. Instead is using django run server which is the issue here. Run server can only have one thread running while asyncio needs to work in multi threading.

**Comment by robertavram** [comment]
I made it work with uwsgi.. for some reason now it's just inconsistent...

**Comment by robertavram** [comment]
@sethgold8 @dfryta sometimes it works...sometimes it doesn't

**Comment by robertavram** [comment]
```
raceback (most recent call last):
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
7/11/2018 4:19:43 PM    response = get_response(request)
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
7/11/2018 4:19:43 PM    response = self._get_response(request)
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
7/11/2018 4:19:43 PM    response = self.process_exception_by_middleware(e, request)
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
7/11/2018 4:19:43 PM    response = wrapped_callback(request, *callback_args, **callback_kwargs)
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
7/11/2018 4:19:43 PM    return view_func(*args, **kwargs)
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
7/11/2018 4:19:43 PM    return self.dispatch(request, *args, **kwargs)
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
7/11/2018 4:19:43 PM    response = self.handle_exception(exc)
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
7/11/2018 4:19:43 PM    self.raise_uncaught_exception(exc)
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
7/11/2018 4:19:43 PM    response = handler(request, *args, **kwargs)
7/11/2018 4:19:43 PM  File "/code/django_api/apps/ocha/views.py", line 59, in get
7/11/2018 4:19:43 PM    response_plans = self.get_response_plans()
7/11/2018 4:19:43 PM  File "/code/django_api/apps/ocha/views.py", line 56, in get_response_plans
7/11/2018 4:19:43 PM    return get_response_plans_for_countries(self.get_country_iso3_codes())
7/11/2018 4:19:43 PM  File "/code/django_api/apps/ocha/imports/bulk.py", line 37, in get_response_plans_for_countries
7/11/2018 4:19:43 PM    results = fetch_json_urls_async(urls_to_retrieve)
7/11/2018 4:19:43 PM  File "/code/django_api/apps/ocha/imports/bulk.py", line 11, in fetch_json_urls_async
7/11/2018 4:19:43 PM    loop = asyncio.get_event_loop()
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
7/11/2018 4:19:43 PM    return get_event_loop_policy().get_event_loop()
7/11/2018 4:19:43 PM  File "/usr/local/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
7/11/2018 4:19:43 PM    % threading.current_thread().name)
7/11/2018 4:19:43 PMRuntimeError: There is no current event loop in thread "b'uWSGIWorker3Core1'".
```

**Comment by sethgold8** [comment]
@robertavram We think 2 potential solutions

* configure uwsgi to work with asyncio
* make it not async (last resort option)

@dfryta

**Comment by sethgold8** [comment]
@n1207n can you add the parameters

**Comment by sethgold8** [comment]
asyncio 10 --greenlet

**Comment by robertavram** [comment]
wondering if there are any updates on this... so far it doesn't work.

**Comment by n1207n** [comment]
A quick update here:

A default PyPi package for uwsgi does not have asyncio plugin. So I had to modify Dockerfile to install uwsgi separately with UWSGI_PROFILE environment variable, along with greenlet thread engine.

I had to modify heavily for Python function that is responsible for importing OCHA response plan data to favor asyncio.coroutine instead of current implementation. I just confirmed my local environment to import a response plan for Iraq 2018 and imported Partner project from OCHA.

I'll make a commit to develop branch so that we can test this on staging environment.

**Comment by robertavram** [comment]
@n1207n got it thanks... seems to work.. I'll have Kunal confirm with QA as well

**Comment by robertavram** [comment]
@n1207n @sethgold8 

it seems like env is going down after a certain number of requests with the new config:

```
7/18/2018 2:34:40 PM*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
7/18/2018 2:34:40 PMyour memory page size is 4096 bytes
7/18/2018 2:34:40 PMdetected max file descriptor number: 1048576
7/18/2018 2:34:40 PM- async cores set to 50 - fd table size: 1048576
7/18/2018 2:34:40 PMlock engine: pthread robust mutexes
7/18/2018 2:34:40 PMthunder lock: disabled (you can enable it with --thunder-lock)
7/18/2018 2:34:40 PMuWSGI http bound on :8000 fd 4
7/18/2018 2:34:43 PMuwsgi socket 0 bound to TCP address 127.0.0.1:43787 (port auto-assigned) fd 3
7/18/2018 2:34:43 PMPython version: 3.6.6 (default, Jul 17 2018, 11:12:33)  [GCC 6.3.0 20170516]
7/18/2018 2:34:43 PMPython main interpreter initialized at 0x55be508ec680
7/18/2018 2:34:43 PMpython threads support enabled
7/18/2018 2:34:43 PMyour server socket listen backlog is limited to 100 connections
7/18/2018 2:34:43 PMyour mercy for graceful operations on workers is 60 seconds
7/18/2018 2:34:43 PMmapped 518400 bytes (506 KB) for 16 cores
7/18/2018 2:34:43 PM*** Operational MODE: preforking+threaded ***
7/18/2018 2:34:44 PM/usr/local/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
7/18/2018 2:34:44 PM  RequestsDependencyWarning)
7/18/2018 2:34:45 PMWSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55be508ec680 pid: 1 (default app)
7/18/2018 2:34:45 PMenabled greenlet engine
7/18/2018 2:34:45 PM*** uWSGI is running in multiple interpreter mode ***
7/18/2018 2:34:45 PMgracefully (RE)spawned uWSGI master process (pid: 1)
7/18/2018 2:34:45 PMspawned uWSGI worker 1 (pid: 315, cores: 4)
7/18/2018 2:34:45 PM*** running asyncio loop engine [addr:0x55be4ff12470] ***
7/18/2018 2:34:45 PMspawned uWSGI worker 2 (pid: 316, cores: 4)
7/18/2018 2:34:45 PMspawned uWSGI worker 3 (pid: 317, cores: 4)
7/18/2018 2:34:45 PMspawned uWSGI worker 4 (pid: 318, cores: 4)
7/18/2018 2:34:45 PMspawned uWSGI http 1 (pid: 319)
7/18/2018 2:34:48 PMGracefully killing worker 3 (pid: 317)...
7/18/2018 2:34:48 PMGracefully killing worker 1 (pid: 315)...
7/18/2018 2:34:48 PMFatal Python error: PyThreadState_Get: no current thread
7/18/2018 2:34:48 PMFatal Python error: PyThreadState_Get: no current thread
7/18/2018 2:34:48 PMGracefully killing worker 2 (pid: 316)...
7/18/2018 2:34:48 PM
7/18/2018 2:34:48 PMCurrent thread 0xFatal Python error: PyThreadState_Get: no current thread
7/18/2018 2:34:48 PM
7/18/2018 2:34:48 PMCurrent thread 0x
7/18/2018 2:34:48 PM00007fadadc67780 (most recent call first):
7/18/2018 2:34:48 PM  File "Current thread 0x/u00007fadadc67780sr (most recent call first):
7/18/2018 2:34:48 PM  File "/usr/local/lib/python3.6/selectors.py", line 445 in select
7/18/2018 2:34:48 PM  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1398 in _run_once
7/18/2018 2:34:48 PM  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 422 in run_forever
```

**Comment by n1207n** [comment]
@robertavram, thanks for the error log. It's quite unfortunate to encounter this.

I think I'm gonna ditch asyncio for response plan import. Even Uwsgi docs suggests that this is experimental feature, so I can see this is not stable.

I'm hoping to convert response plan import to celery task function just like how OCHA data is getting imported in such manner.

**Comment by n1207n** [comment]
In PRP, we already have nginx & uwsgi setup for both docker-compose and k8s. Changing to gunicorn would require more efforts in my opinion.

I'm simply gonna replicate what we already have for other OCHA API data load without changing webservers. that's all ;)

**Comment by KKaselkar** [comment]
@sethgold8  sent you the list of partners to have OCHA ref ID added in django admin.

**Comment by KKaselkar** [comment]
OCHA add projects works for Syria for the ID you provided for a partner
