### ISSUE TITLE
Annex C form must be generated when the partner submits a QPR

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#964]
Currently annex C form is generated in PRP when a QPR is accepted in PMP.

- [ ] Annex C form must be generated when the report is submitted in PRP , this used to work before but has changed now

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46688948-acf05a80-cbcc-11e8-967d-8273382dd16a.png)

**Comment by sethgold8** [comment]
the 'download Annex C' button does not work? @KKaselkar

**Comment by KKaselkar** [comment]
Annex C link is not displayed in PRP until and unless report is accepted in PMP, earlier it used to generate and display the Annex C link as soon as partner used to submit the report.

**Comment by sethgold8** [comment]
This may be a permission issue

**Comment by groinder** [comment]
The issue was related to ID management permissions changes, I simplified some of the permissions checks although I misinterpreted this one. It's fixed now.

**Comment by sethgold8** [comment]
@groinder is there a specific PR for this? Still seeing without Download Annex C
![Screen Shot 2018-10-11 at 2.38.53 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f26b7191a37af111234f5a5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df542e34456ad163466ee7e2431.png)

**Comment by sethgold8** [comment]
@groinder we believe it only looks for 'accepted' status. It should also look for 'Submitted'

**Comment by groinder** [comment]
@sethgold8 It is fixed with https://github.com/unicef/etools-partner-reporting-portal/commit/0aa4544ecd353d11ce34b50101637229d5b760bb @n1207n  I've look into the sources on https://dev.partnerreportingportal.org for some reason it doesn't have this change there.

**Comment by sethgold8** [comment]
Fixed :)

![Screen Shot 2018-10-15 at 1.04.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f66b7191a379f1122f4f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df542e74e56ad123266ee752431.png)

**Comment by KKaselkar** [comment]
Annex C form is generated when the report is submitted
